# Generated by Django 5.2.4 on 2025-09-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_pages', '0003_store_alter_product_store_id'),
        ('users', '0003_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market_pages.store'),
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
