# Generated by Django 5.2.4 on 2025-09-10 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_pages', '0002_product_store_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('market_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='market_pages.store'),
        ),
    ]
