# Generated by Django 5.2.4 on 2025-09-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_pages', '0003_store_alter_product_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
