# Generated by Django 5.2.4 on 2025-09-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_pages', '0004_alter_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
