# Generated by Django 5.2.4 on 2025-09-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_pages', '0005_remove_cart_cart_id_alter_cart_buyer'),
        ('market_pages', '0005_store_logo'),
    ]

    operations = [
    ]
